---
- name: Check variables
  assert:
    that:
      - yum_upgrade_security == "yes" or yum_upgrade_security == "no"

- name: Upgrade packages
  dnf:
    name: "*"
    state: latest
    security: "{{ yum_upgrade_security }}"

- name: Check for reboot hint.
  shell: LAST_KERNEL=$(rpm -q --last kernel | awk 'NR==1{sub(/kernel-/,""); print $1}'); CURRENT_KERNEL=$(uname -r); if [ $LAST_KERNEL != $CURRENT_KERNEL ]; then echo 'reboot'; else echo 'no'; fi
  ignore_errors: true
  register: reboot_hint

- name: Rebooting ...
  reboot:
  when: reboot_hint.stdout.find("reboot") != -1
  register: rebooting

- name: Wait for reboot to complete
  wait_for_connection:
